namespace Dexla.Common.Types.Enums;

public enum CardStyleTypes
{
    ROUNDED,
    SQUARED,
    OUTLINED,
    ELEVATED,
    OUTLINED_ROUNDED,
    OUTLINED_SQUARED,
    OUTLINED_ELEVATED,
    ELEVATED_ROUNDED,
    ELEVATED_SQUARED,   
    ELEVATED_OUTLINED_ROUNDED,
    ELEVATED_OUTLINED_SQUARED,
}