name: Common Editor - Pack and Publish

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "The resultant version for this package"
        required: true

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 7.0.x
      BUILD_PATH: ./src/Dexla.Common.Editor.Entities/Dexla.Common.Editor.Entities.csproj
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Add nuget feed
        run: dotnet nuget add source --username ${{ secrets.PACKAGE_USER }} --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dexla-inc/index.json"

      - name: Install dependencies
        run: dotnet restore ${{ env.BUILD_PATH }}

      - name: Build
        run: dotnet build ${{ env.BUILD_PATH }} --configuration Release

      - name: Pack
        run: dotnet pack ${{ env.BUILD_PATH }} --configuration Release --no-restore --no-build -p:Version=${{ github.event.inputs.packageVersion }} --output nupkgs

      - name: Push
        run: dotnet nuget push nupkgs/*.nupkg --source https://nuget.pkg.github.com/dexla-inc/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
